
package cn.raiyee.hanergy.todo.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-06T10:08:23.244+08:00
 * Generated source version: 3.2.6
 */

@WebFault(name = "Exception", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/")
public class Exception_Exception extends java.lang.Exception {

    private Exception exception;

    public Exception_Exception() {
        super();
    }

    public Exception_Exception(String message) {
        super(message);
    }

    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public Exception getFaultInfo() {
        return this.exception;
    }
}
