package cn.raiyee.hanergy.todo.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-06T10:08:23.252+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", name = "ISysNotifyTodoWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface ISysNotifyTodoWebService {

    @WebMethod
    @RequestWrapper(localName = "deleteTodo", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "cn.raiyee.hanergy.todo.client.DeleteTodo")
    @ResponseWrapper(localName = "deleteTodoResponse", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "cn.raiyee.hanergy.todo.client.DeleteTodoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public NotifyTodoAppResult deleteTodo(
            @WebParam(name = "arg0", targetNamespace = "")
                    NotifyTodoRemoveContext arg0
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "getTodoCount", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "cn.raiyee.hanergy.todo.client.GetTodoCount")
    @ResponseWrapper(localName = "getTodoCountResponse", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "cn.raiyee.hanergy.todo.client.GetTodoCountResponse")
    @WebResult(name = "return", targetNamespace = "")
    public NotifyTodoAppResult getTodoCount(
            @WebParam(name = "arg0", targetNamespace = "")
                    cn.raiyee.hanergy.todo.client.NotifyTodoGetCountContext arg0
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "setTodoDone", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "cn.raiyee.hanergy.todo.client.SetTodoDone")
    @ResponseWrapper(localName = "setTodoDoneResponse", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "cn.raiyee.hanergy.todo.client.SetTodoDoneResponse")
    @WebResult(name = "return", targetNamespace = "")
    public NotifyTodoAppResult setTodoDone(
            @WebParam(name = "arg0", targetNamespace = "")
                    NotifyTodoRemoveContext arg0
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "getTodo", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "cn.raiyee.hanergy.todo.client.GetTodo")
    @ResponseWrapper(localName = "getTodoResponse", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "cn.raiyee.hanergy.todo.client.GetTodoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public NotifyTodoAppResult getTodo(
            @WebParam(name = "arg0", targetNamespace = "")
                    NotifyTodoGetContext arg0
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "sendTodo", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "cn.raiyee.hanergy.todo.client.SendTodo")
    @ResponseWrapper(localName = "sendTodoResponse", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "cn.raiyee.hanergy.todo.client.SendTodoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public NotifyTodoAppResult sendTodo(
            @WebParam(name = "arg0", targetNamespace = "")
                    NotifyTodoSendContext arg0
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "updateTodo", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "cn.raiyee.hanergy.todo.client.UpdateTodo")
    @ResponseWrapper(localName = "updateTodoResponse", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", className = "cn.raiyee.hanergy.todo.client.UpdateTodoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public NotifyTodoAppResult updateTodo(
            @WebParam(name = "arg0", targetNamespace = "")
                    NotifyTodoUpdateContext arg0
    ) throws Exception_Exception;
}
